server { 
    listen 80; 
    server_name_; 
    
    root /var/www/html;
    index index.html; 
    
    location /status {
        alias /var/log/server-health; 
        index status.html; 
    }
    
    location ~* \.log(/.gz)?$ {
        deny all
        return 403;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    access_log /var/log/nginx/heath-access.log;
    error_log /var/log/nginx/health-error.log;
}
